### PR TITLE
Added possible missing null check. (Attempt to invoke virtual method 'boolean android.…

### PR DESCRIPTION
**Pull request by lorand-brookvale**
…bluetooth.BluetoothGatt.discoverServices()' on a null object reference)

### CODE REVIEW

**Comment by weliem** [comment]
Hi, thanks for the PR

Did you actually see a Null Pointer Exception happen? I don't really understand how that can happen....

**Comment by lorand-brookvale** [comment]
> Hi, thanks for the PR
> 
> Did you actually see a Null Pointer Exception happen? I don't really understand how that can happen....

me neither, but i got the following, am i missing something? 
picture: https://we.tl/t-06fN4ejLGC

**Comment by weliem** [comment]
Ok, so it did happen then....can you share a log or something so I can see what happened?

**Comment by lorand-brookvale** [comment]
> Ok, so it did happen then....can you share a log or something so I can see what happened?

Hi,
I only have that screenshot.

**Pull request merged**
